In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Python/Pandas/sales_data.csv")

In [ ]:
#Basic Data Exploration
#1.	Load the sales data CSV file into a Pandas DataFrame.
df = pd.read_csv("/content/drive/MyDrive/Python/Pandas/sales_data.csv")

#2.	Display the first 5 rows of the DataFrame.
df.head()

#3.	Show the last 5 rows of the DataFrame.
df.tail()

#4.	Get the shape (number of rows and columns) of the dataset.
df.shape

#5.	Display summary statistics of all numerical columns.
df.describe()

#6.	Get column names of the dataset.
a= list(df.columns)
# print(a)

#7.	Check for missing values in the dataset.
df.isnull().sum()

#8.	Get the data types of each column.
df.dtypes

#9.	Sort the dataset by SalesAmount in descending order.
df.sort_values("SalesAmount", ascending = False)

#10.	Select only EmployeeID, Name, and SalesAmount columns.
df[['EmployeeID','Name', 'SalesAmount']].head(1)

   EmployeeID        Name  SalesAmount
0        1001  Employee_1        34200

In [ ]:

#Filtering & Conditional Selection ( SQL limit , Sort asc desc , Where )
#11.	Find all employees who achieved their sales target.
df.head()
df[df['TargetAchieved'] == "Yes"]

#12.	Find employees who belong to the "Electronics" department.
df[df['Department'] == 'Electronics']

#13.	Find employees who belong to the "West" region and achieved their target.
df[(df['Region']=="West") & (df['TargetAchieved']=="Yes")]

#14.	Filter employees who have a SalesAmount greater than 30,000.
df[df['SalesAmount'] > 30000].head()

#15.	Find employees who have a commission percentage greater than 5%.
df[df['CommissionPercentage']>5]

#16.	Find employees who did not achieve their target.
df[df['TargetAchieved']=="No"]

#17.	Find employees who belong to either "Groceries" or "Automobile" department.
df[(df['Department'] == 'Groceries') | (df['Department'] == 'Automobile')]


#18.	Find employees with TotalEarnings greater than 40,000.
df[df['TotalEarnings'] > 40000]

#19.	Find employees who are older than 40 years and achieved their target.
df[(df["Age"]>40 ) & (df["TargetAchieved"]=="Yes")]

#20.	Select employees whose names contain "10".
df[df["Name"].str.contains("10")]

,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings,AboveAverageEarnings
9,Employee_10,52,Electronics,East,18766,14392,Yes,4,19516.64,No

In [ ]:
#Aggregation & Grouping ( Pivot , Group by )
#21.	Find the average sales amount per department.
df.groupby("Department")["SalesAmount"].mean()

#22.	Count the number of employees in each region.
df.groupby("Region")["EmployeeID"].count()

#23.	Find the highest SalesAmount in each department.
df.groupby("Department")["SalesAmount"].max()

#24.	Find the lowest SalesAmount in each department.
df.groupby("Department")["SalesAmount"].min()

#25.	Find the employee with the highest total earnings.
df.nlargest(1, "TotalEarnings")

#df.sort_values("TotalEarnings", ascending=False).head(1)

#26.	Count the number of employees who achieved and did not achieve their target.
df.groupby("TargetAchieved")["EmployeeID"].count()
# or
#df["TargetAchieved"].value_counts()
#df.groupby("TargetAchieved").size()

#27.	Find the average commission percentage per department.
df.groupby("Department")["CommissionPercentage"].mean()

#28.	Find the highest TotalEarnings per region.
df.groupby("Region")["TotalEarnings"].max()

#29.	Find the lowest TotalEarnings per department.
df.nsmallest(1,"TotalEarnings")

#30.	Count the number of employees per department.
df.groupby("Department")["EmployeeID"].count()

df.head()

,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings,AboveAverageEarnings
0,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00,Yes
1,Employee_2,26,Home Decor,East,32850,42821,Needs Improvement,9,35806.50,Yes
2,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34,Yes
3,Employee_4,31,Electronics,West,17263,40183,Needs Improvement,3,17780.89,No
4,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08,Yes

In [ ]:
df.head()

,Name,Age,Department,Region,SalesAmount,Target,TargetAchieved,CommissionPercentage,TotalEarnings,AboveAverageEarnings
0,Employee_1,28,Electronics,North,34200,17968,Yes,5,35910.00,Yes
1,Employee_2,26,Home Decor,East,32850,42821,Needs Improvement,9,35806.50,Yes
2,Employee_3,22,Home Decor,South,43267,40728,Yes,2,44132.34,Yes
3,Employee_4,31,Electronics,West,17263,40183,Needs Improvement,3,17780.89,No
4,Employee_5,49,Groceries,East,37427,17010,Yes,4,38924.08,Yes

In [ ]:
#Data Transformation
#31.	Remove the EmployeeID column from the DataFrame.
#df.drop(columns="EmployeeID",inplace = True)

#32.	Reset the index of the DataFrame.
df.reset_index(drop=True, inplace = True)

#33.	Replace all employees who did not achieve the target with "Needs Improvement" in the TargetAchieved column.
df["TargetAchieved"].replace( "Needs Improvement","No")

df.loc[df['TargetAchieved'] == 'No', 'TargetAchieved'] = 'Needs Improvement'

#34.	Create a new column PerformanceLevel with values: "High" if SalesAmount > 40000, "Medium" if between 20000-40000, else "Low".
#df["PerformanceLevel"] = df['SalesAmount'].apply(lambda i : "High" if i > 40000 else ("Meduim" if i > 20000 else "Low"))

#35.	Convert Age column to an integer type.
df["Age"]=df['Age'].astype(int)
df["Age"].dtype

#36.	Create a new column AboveAverageEarnings, which is "Yes" if TotalEarnings is above the average.
df["AboveAverageEarnings"] = df["TotalEarnings"].apply(lambda i : "Yes" if i > df["TotalEarnings"].mean() else "No")

#37.	Convert the Department column to a categorical data type.
df['Department'].astype('category')
df['Department'].dtype

#38.	Find the top 5 employees based on total earnings.
#df.sort_values("TotalEarnings", ascending = False).head(5)
# OR
df.nlargest(5,'TotalEarnings')

#39.	Find the bottom 5 employees based on total earnings.
df.nsmallest(5,"TotalEarnings")

#40.	Save the modified DataFrame to a new CSV file.
df.to_csv(" Modified_Sales.csv", index = False)